# Homebrew formula for the MungerWare-packaged opencode binary.
#
# This file is regenerated by the MungerWare Publish workflow
# (munger-publish.yml) on every release, which computes the sha256 of the
# built darwin-arm64 binary and writes it below. The URL points at the
# matching release asset, so the version and checksum always travel together.

class Opencode < Formula
  desc "MungerWare-packaged opencode, the open source AI coding agent"
  homepage "https://github.com/Munger/opencode"
  url "https://github.com/Munger/opencode/releases/download/v1.18.15-mw.1/opencode-darwin-arm64"
  version "1.18.15-mw.1"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license "MIT"

  def install
    bin.install "opencode-darwin-arm64" => "opencode"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/opencode --version")
  end
end
